"use client"

import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/shared/Header";
import Footer from "./components/shared/Footer";
import MaxWidthWrapper from "./utils/MaxWidthWrapper";
import { usePathname } from "next/navigation";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// {navbarAndFooter ? (
//   <Providers>
//     <NavBar />
//     {children}
//     <Footer />
//   </Providers>
// ) : (
//   children
// )}

export default function RootLayout({ children }) {
  const targetPath = usePathname();

  const headerAndFooter = ![
    '/builder',
  ].includes(targetPath);

  return (
    <html lang="en">
      <body className={inter.className}>
        {headerAndFooter ? (
          <MaxWidthWrapper>
            <Header />
            {children}
            <Footer />
          </MaxWidthWrapper>
        ) : (
          children
        )}
      </body>
    </html>
  );
}

{/* <MaxWidthWrapper>
<Header />
{children}
<Footer />
</MaxWidthWrapper> */}