import { AiOutlineDownload } from "react-icons/ai";
import { CiEdit } from "react-icons/ci";
import { GoArrowLeft } from "react-icons/go";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const ResumeEditLayout = ({ children }) => {
  return (
    <html lang="en">
      <body>
        <div className=" bg-[#0072B1] px-4">
          <div className="flex justify-between items-center w-full h-20">
            <div className="flex justify-around items-center space-x-2 bg-white py-2 px-4 rounded shadow text-blue text-lg text-blue-400 font-medium cursor-pointer">
              <GoArrowLeft className="w-6 h-6" />
              <button className="hidden md:block">Dashboard</button>
            </div>

            <div className="flex justify-around items-center text-white space-x-2">
              <p className="text-lg font-medium hidden md:block">Cv Name</p>
              <CiEdit className="w-6 h-6 cursor-pointer" />
            </div>

            <div className="flex justify-around items-center space-x-2 bg-white py-2 px-4 rounded shadow text-blue text-lg text-blue-400 font-medium cursor-pointer">
              <button className="hidden md:block">Download</button>
              <AiOutlineDownload className="w-6 h-6" />
            </div>
          </div>
        </div>

        {/* childern  */}
        <div>{children}</div>
      </body>
    </html>
  );
};
export default ResumeEditLayout;
